// <auto-generated />
namespace ADProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AssignRole_FK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AssignRole_FK));
        
        string IMigrationMetadata.Id
        {
            get { return "202002101216595_AssignRole_FK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
