// <auto-generated />
namespace ADProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class employee_assignRole_1to1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(employee_assignRole_1to1));
        
        string IMigrationMetadata.Id
        {
            get { return "202002110556455_employee_assignRole_1to1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
